const ADD_TRANSACTION = "ADD_TRANSACTION";
const DELETE_TRANSACTION = "DELETE_TRANSACTION";
const CHANGE_TRANSACTION = "CHANGE_TRANSACTION";

export default {
  ADD_TRANSACTION,
  DELETE_TRANSACTION,
  CHANGE_TRANSACTION
};
